// Generated by gencpp from file actions_quiz/CustomActionMsgResult.msg
// DO NOT EDIT!


#ifndef ACTIONS_QUIZ_MESSAGE_CUSTOMACTIONMSGRESULT_H
#define ACTIONS_QUIZ_MESSAGE_CUSTOMACTIONMSGRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actions_quiz
{
template <class ContainerAllocator>
struct CustomActionMsgResult_
{
  typedef CustomActionMsgResult_<ContainerAllocator> Type;

  CustomActionMsgResult_()
    {
    }
  CustomActionMsgResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> const> ConstPtr;

}; // struct CustomActionMsgResult_

typedef ::actions_quiz::CustomActionMsgResult_<std::allocator<void> > CustomActionMsgResult;

typedef boost::shared_ptr< ::actions_quiz::CustomActionMsgResult > CustomActionMsgResultPtr;
typedef boost::shared_ptr< ::actions_quiz::CustomActionMsgResult const> CustomActionMsgResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace actions_quiz

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::actions_quiz::CustomActionMsgResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actions_quiz/CustomActionMsgResult";
  }

  static const char* value(const ::actions_quiz::CustomActionMsgResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
;
  }

  static const char* value(const ::actions_quiz::CustomActionMsgResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomActionMsgResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actions_quiz::CustomActionMsgResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::actions_quiz::CustomActionMsgResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONS_QUIZ_MESSAGE_CUSTOMACTIONMSGRESULT_H
